# Auto update
auto-update: true

# Enable debug logs
debug: false

# Default Bump language (Available languages: https://github.com/SlimefunGuguProject/Bump#supported-languages)
# SlimefunTranslation is supported
lang: en

# Enable researches
enable-researches: true

# Weapon settings
weapons:
  # The duration of projectiles launched by any Bump weapon (in Slimefun ticks)
  projectile-duration: 10

appraiser:
  # Broadcast the appraisal result to the whole server
  broadcast:
    enabled: true
    # The required number of stars to broadcast the appraisal result to everyone
    star-requirement: 7
